INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_STELLARSTATION stellarstation)

FIND_PATH(
    STELLARSTATION_INCLUDE_DIRS
    NAMES stellarstation/api.h
    HINTS $ENV{STELLARSTATION_DIR}/include
        ${PC_STELLARSTATION_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    STELLARSTATION_LIBRARIES
    NAMES gnuradio-stellarstation
    HINTS $ENV{STELLARSTATION_DIR}/lib
        ${PC_STELLARSTATION_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STELLARSTATION DEFAULT_MSG STELLARSTATION_LIBRARIES STELLARSTATION_INCLUDE_DIRS)
MARK_AS_ADVANCED(STELLARSTATION_LIBRARIES STELLARSTATION_INCLUDE_DIRS)

